<div class="container mt-5">
    <div class="row">
        <div class="col-12 text-center">
            <h4><strong>More Artificial Intelligence From BoredHumans.com:</strong></h4>
        </div>
        <div class="col">
            <ul>
                <li><a href="/lyrics_generator.php" target="new"><strong>Lyrics Generator</strong></a> - Our AI writes hit songs.</li>
                <li><a href="/art.php" target="new"><strong>AI Paintings</strong></a> - Our AI creates art.</li>
                <li><a href="/falling_sand.php" target="new"><strong>Falling Sand</strong></a> - Play with lava, water, napalm and more.</li>
                <li><a href="/farts.php"><strong>AI Farts</strong></a> - What do robot farts sound like?</li>
                <li><a href="/apes.php" target="new"><strong>BoredHumans Apes</strong></a> - Apes that do not exist.</li>
                <li><a href="/tv_shows.php" target="new"><strong>TV Episode Generator</strong></a> - The Simpsons, Friends, Game of Thrones and more.</li>
                <li><a href="/movies.php" target="new"><strong>AI Colorized Movies</strong></a> - Watch classic films for free.</li>
                <li><a href="/faces.php" target="new"><strong>Fake People</strong></a> - AI-generated faces.</li>
                <li><a href="/word_generator.php" target="new"><strong>New Words</strong></a> - These words do not exist.</li>
                <li><a href="/photo_blender.php" target="new"><strong>Photo Blender</strong></a> - Two beautiful photos combined into one.</li>
                <li><a href="/interactive_fiction.php"><strong>Interactive Fiction</strong></a> - A "choose your own ending" story written by our AI.</li>
                <li><a href="/metal_lyrics_generator.php" target="new"><strong>Heavy Metal Lyrics Generator</strong></a> - Our AI rocks!</li>
                <li><a href="/quotes.php" target="new"><strong>Quote Generator</strong></a> - AI thoughts to inspire you.</li>
                <li><a href="/deepfakes.php" target="new"><strong>Deepfake Videos</strong></a> - Elon Musk in Reefer Madness, Joe Exotic - Lost Movie Footage, and Logan Paul - Tiger King.</li>
                <li><a href="/pizza.php" target="new"><strong>This Pizza Does Not Exist</strong></a> - Generated by a computer.</li>
                <li><a href="/game_idea_generator.php"><strong>Video Game Ideas</strong></a> - Our AI thinks up new gamli.
                <li><a href="/dreams.php" target="new"><strong>AI Dreams</strong></a> - What does a computer dream?</li>
                <li><a href="/movie_plots.php" target="new"><strong>Movie Plot Generator</strong></a> - Movies that do not exist.</li>
                <li><a href="/music.php" target="new"><strong>AI Music</strong></a> - Listen to music our AI created</li>
                <li><a href="/research_papers.php" target="new"><strong>Academic Paper Generator</strong></a> - The AI writes papers like on arXiv.org.</li>
                <li><a href="/anime_stories.php" target="new"><strong>Anime Stories</strong></a> - Read an AI-generated anime story.</li>
                <li><a href="/video_montages.php" target="new"><strong>Movie Montage Maker</strong></A> - Type a word or phrase.</li>
                <li><a href="/insults.php" target="new"><strong>Insult Battle</strong></a> - We dare you to insult our AI.</li>
                <li><a href="/poetry_generator.php" target="new"><strong>Poetry Generator</strong></a> - Our AI is a poet.</li>
                <li><a href="/metal_website.php" target="new"><strong>Website To Heavy Metal Song Converter</strong></a> - Enter a URL.</li>
                <li><a href="/happy.php" target="new"><strong>Happy Moments</strong></a> - What makes humans happy?</li>
                <li><a href="/band_name_generator.php" target="new"><strong>Band Name Generator</strong></a> - Hundreds of fun band names.</li>
                <li><a href="/jokes.php" target="new"><strong>Joke Battle</strong></a> - Can you tell a better joke than our AI?</li>
                <li><a href="/business_ideas.php" target="new"><strong>Business Ideas</strong></a> - Our AI will help you make money.</li>
                <li><a href="/meme_generator.php" target="new"><strong>Meme Generator</strong></a> - Memes written by an AI.</li>
                <li><a href="/story_generator.php" target="new"><strong>Story Generator</strong></a> - Our AI will tell you a story.</li>
                <li><a href="/neural_style_transfer.php" target="new"><strong>Neural Style Transfer</strong></a> - Photos turned into paintings.</li>
                <li><a href="/baby_name_generator.php" target="new"><strong>Baby Name Generator</strong></a> - Unique baby names.</li>
                <li><a href="/fortune_cookies.php" target="new"><strong>Fortune Cookies</strong></a> - Our AI knows your future.</li>
                <li><a href="/yelling.php" target="new"><strong>Get Yelled At</strong></a> - Our AI will get mad at you.</li>
                <li><a href="/anime_images.php" target="new"><strong>Waifu Images</strong></a> - These anime characters do not really exist.</li>
                <li><a href="/inventions.php" target="new"><strong>Invention Generator</strong></a> - Ideas for new products.</li>
                <li><a href="/dogs.php" target="new"><strong>Fake Dogs</strong></a> - AI-generated dogs.</li>
                <li><a href="/superhero.php" target="new"><strong>Superhero Name Generator</strong></a> - Find your superhero name.</li>
                <li><a href="/confessions.php" target="new"><strong>Confessions</strong></a> - Our AI has secrets.</li>
                <li><a href="/writing_prompts.php" target="new"><strong>Writing Prompts</strong></a> - Our AI starts the story, you finish it.</li>
                <li><a href="/patents.php" target="new"><strong>Patent Generator</strong></a> - Turn any website into a patent application.</li>
                <li><a href="/video_articles.php" target="new"><strong>Video Articles</strong></a> - Brought to life by AI.</li>
                <li><a href="/anagrams.php" target="new"><strong>Anagram Generator</strong></a> - Words formed by rearranging the letters.</li>
                <li><a href="/domain_appraisals.php"><strong>Domain Name Appraisals</strong></a> - Curious what a domain name is worth? Instantly find out the value using AI.</li>
                <li><a href="/chat.php"><strong>Chat Bot</strong></a> - Talk with our AI about anything you want.</li>
                <li><a href="/games.php" target="new"><strong>AI Games</strong></a> - Pong, Slime Volleyball, and more.</li>
                <li><a href="/demos.php" target="new"><strong>AI Demos</strong></a> - See how machine learning and genetic algorithms work.</li>
           
                <li><strong>Coming Soon - Text-To-Image Generator</strong></a> - Turn words into images.</li>
                <li><strong>Coming Soon - AI Predictions</strong></a> - We use machine learning to predict the winner of sports games and the prices of stocks and crypto coins.</li>
                <li><strong>Coming Soon - NFT Search Engine</strong></a> - Powered by AI.</li>
                <li><strong>Coming Soon - ML Datasets</strong></a> - A search engine of free machine learning datasets to use to train models.</li>
                <li><a href="/ai_projects.php"><strong>Coming Soon - AI Projects</strong></a> - Make your own gadgets and inventions for less than $100, such as a self-driving car or boat.</li>
            </ul>

            <br>
            <p class="text-center"><a href="https://boredhumans.com">Back To BoredHumans.com Main Page</a></p>
           
            <br><br>
            Most machine learning programs run locally on a data scientist's PC or server, in programming languages such as Python, C++, or Java, and are not made to be accessed via a web page. We created BoredHumans.com specifically to showcase AI to the general public over the Internet.
            
            <br><br>
            <div class="text-center">   
                <a target="_blank" href="https://instagram.com/boredhumansai/"><img src="/ord/assets/images/instagram.png" height="48" width="48"></a>
                <a target="_blank" href="https://twitter.com/boredhumansai/"><img src="/ord/assets/images/twitter.png" height="48" width="48"></a>
                <a target="_blank" href="https://facebook.com/BoredHumansAI/"><img src="/ord/assets/images/facebook.png" height="48" width="48"></a>
                <a target="_blank" href="https://pinterest.com/boredhumansai/"><img src="/ord/assets/images/pinterest.png" height="48" width="48"></a>
                
                <p><a href="https://boredhumans.com/privacy.php" target="new">Privacy Policy</a></p>

                <br>
                (We do not save your info, sell your personal data, or do anything else to violate your privacy)
                <br><br>
                <p>Copyright: The design of this site is Copyright 2022 by BoredHumans.com.</p>
                <p>BoredHumans.com is owned by:</p>
                <p>Impulse Communications, Inc.</p>
                <p>9450 SW Gemini Dr. #56742</p>
                <p>Beaverton, OR 97008</p>
                <p>Email: <a href="mailto:eric@boredhumans.com">eric@boredhumans.com</a></p>
            </div>
            
            
           

</div>
    </div>
</div> 